---
- hosts: chip
  tasks:

   - name: Install python for CHIP GPIO_IO python library
     action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
     with_items:
        - git
        - build-essential
        - python3-dev
        - python3-pip
        - flex
        - bison
        - chip-dt-overlays